version: "3.7"

services:
  redis:
    image: redis:7.0.2-alpine
    container_name: ${PROJECT_NAME}-redis
    restart: unless-stopped
    env_file:
      - ./.env
  web:
    build: .
    command: sh -c "python manage.py migrate &&
      yes | python manage.py collectstatic --no-input &&
      gunicorn ${PROJECT_NAME}.wsgi:application --workers=${GUNICORN_WORKERS} --timeout=${GUNICORN_TIMEOUT} --bind 0.0.0.0:${GUNICORN_PORT}"
    container_name: ${PROJECT_NAME}-web

    volumes:
      - .:/app
      - static_volume:/app/static
    env_file:
      - ./.env
    ports:
      - "8000:8000"
    depends_on:
      - redis
    restart: "on-failure"

  nginx:
    build: ./nginx
    container_name: ${PROJECT_NAME}-nginx
    volumes:
      - static_volume:/app/static
    ports:
      - 80:80
    depends_on:
      - web
    restart: "on-failure"

volumes:
  static_volume: