# Generated by Django 4.1.7 on 2023-04-28 23:47

import applications.common.utils.handler
import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='UUID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='Updated time')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='Created time')),
                ('app_name', models.CharField(default=applications.common.utils.handler.get_app_name, max_length=255, verbose_name='App Name')),
                ('app_version', models.CharField(default=applications.common.utils.handler.get_version, max_length=100, validators=[django.core.validators.RegexValidator(message='Phone number must be entered in the format: 111.222.333 ', regex='^(\\d+)\\.(\\d+)(?:\\.(\\d+))?(?:\\-(\\w+))?$')], verbose_name='App Version')),
                ('maintenance_mode', models.BooleanField(default=False, verbose_name='Maintenance mode')),
            ],
            options={
                'verbose_name': 'Configuration',
                'verbose_name_plural': 'Configurations',
            },
        ),
    ]
